// <auto-generated />
using System;
using ImageProcessor.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImageProcessor.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PostgresqlDbContext))]
    [Migration("20240207234039_ContentTypeToFileMetadata")]
    partial class ContentTypeToFileMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImageProcessor.Domain.Entities.FileMetadata", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("file_name");

                    b.Property<short>("FileType")
                        .HasColumnType("smallint")
                        .HasColumnName("file_type");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.HasKey("FileId");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("file_metadata", "processor");
                });

            modelBuilder.Entity("ImageProcessor.Domain.Entities.ProcessEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("FaildMessage")
                        .HasColumnType("text")
                        .HasColumnName("faild_message");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("Input")
                        .HasColumnType("json")
                        .HasColumnName("input");

                    b.Property<string>("Output")
                        .HasColumnType("json")
                        .HasColumnName("output");

                    b.Property<short>("ProcessStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("process_status");

                    b.Property<short>("ProcessType")
                        .HasColumnType("smallint")
                        .HasColumnName("process_type");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.HasKey("EventId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("FileId");

                    b.ToTable("process_event", "processor");
                });

            modelBuilder.Entity("ImageProcessor.Domain.Entities.ProcessEvent", b =>
                {
                    b.HasOne("ImageProcessor.Domain.Entities.FileMetadata", "FileMetadata")
                        .WithMany("ProcessEvents")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileMetadata");
                });

            modelBuilder.Entity("ImageProcessor.Domain.Entities.FileMetadata", b =>
                {
                    b.Navigation("ProcessEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
